### ISSUE TITLE
Auto Water Nearby Crops in JOE 1.0.1-beta

### ISSUE THREAD

**Issue by L1ghtWalker** [pomepome/JoysOfEfficiency#1]
When i'm plant seed in console infinitely spamming this, until i'm watering crops by myself.

> [JoysOfEfficiency] This mod failed in the GameEvents.UpdateTick event. Technical details:
System.Exception: Couldn't set the value of the StardewValley.TerrainFeatures.HoeDirt::state field ---> System.ArgumentException: Невозможно преобразовать объект типа "System.Int32" к типу "Netcode.NetInt".
   в System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   в System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   в System.Reflection.RtFieldInfo.InternalSetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture, StackCrawlMark& stackMark)
   в System.Reflection.RtFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
   в StardewModdingAPI.Framework.Reflection.ReflectedField``1.SetValue(TValue value) в C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Reflection\ReflectedField.cs:строка 81
   --- Конец трассировки внутреннего стека исключений ---
   в StardewModdingAPI.Framework.Reflection.ReflectedField`1.SetValue(TValue value) в C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Reflection\ReflectedField.cs:строка 89
   в JoysOfEfficiency.ModEntry.OnGameUpdate(Object sender, EventArgs args)
   в StardewModdingAPI.Framework.Events.ManagedEvent.Raise() в C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Events\ManagedEvent.cs:строка 110

**Comment by pomepome** [comment]
Thank you for your report, and that problem should be fixed in 1.1.0-beta.
Try it!

**Comment by L1ghtWalker** [comment]
Yep, now its work.

**Comment by pomepome** [comment]
That's good
