### ISSUE TITLE
Undocumented settings

### ISSUE THREAD

**Issue by Erquint** [pomepome/JoysOfEfficiency#10]
`config.json` keys `AutoRefillWateringCan` and `ShowMousePositionWhenAssigningLocation` are undocumented in `FeaturesAndConfigs.md`.
Additionally, instead of `AutoPickUpTrash` you mistakenly wrote `PauseWhenIdle` in the `FeaturesAndConfigs.md`, so, technically, also undocumented.

Also, it's scarily unclear how the `AutoDepositIngredient` function decides items to be deposited.
Will it just dump the first thing it can into a preserves jar, for example?
If above is the case, I'd rather keep it off but can then a separate setting be added for simpler things like putting bait into crab pots, since this mod already gathers from them? Preferably, taking the bait straight from the fishing rod's own inventory where it's most convenient to keep.

**Comment by pomepome** [comment]
AutoDepositIngredient tries to put item selected in the hotbar into a machine.
So, it won't take baits from fishing rod's inventory.

**Comment by pomepome** [comment]
I'm reviewing documentation now, so please wait for a while.

**Comment by pomepome** [comment]
I updated FeaturesAndConfigs.md.
Thank you for reporting!
