### ISSUE TITLE
hotkey or menu to toggle automatic functions

### ISSUE THREAD

**Issue by sdaugherty** [pomepome/JoysOfEfficiency#2]
would be helpful if the automation could be controlled by a hotkey or menu - occasionally, there are crops that shouldn't be autoharvested, or I want to save energy for activities off the farm and let the other farmhands in my game deal with the crops.

having to restart the game to change settings is rather inconvenient in multiplayer, as is not being able to walk through certain parts of my farm

**Comment by pomepome** [comment]
I added Settings Menu on stable version 1.0.13, and currently working on beta

**Comment by pomepome** [comment]
I added it to beta version at JOE 1.1.4-beta
