### ISSUE TITLE
SMAPI 2.8 Beta 3 no longer functional with JoysOfEfficiency

### ISSUE THREAD

**Issue by ChrisK4** [pomepome/JoysOfEfficiency#5]
It simply skips over the mod in SMAPI now if you have the newest versions of SMAPI and the newest versions of Stardew Valley. Is that intentional?

**Comment by pomepome** [comment]
stable version of JoE does not support 1.3.29 and SMAPI 2.8-beta.
But  you can download beta version at [Release page](https://github.com/pomepome/JoysOfEfficiency/releases), and I think it works.
