### ISSUE TITLE
JoE doesn't seem to support gamepad input

### ISSUE THREAD

**Issue by rmenessec** [pomepome/JoysOfEfficiency#6]
Could you add support for the new SMAPI 2.x input model? I'd like to remap KeyShowMenu to something other than a keyboard key—seeing as a I have a lot of mods installed—but JoE crashes when I set the config line to:
```
"KeyShowMenu": "RightStick",
```
... following [the instructions](https://stardewvalleywiki.com/Modding:Player_Guide/Key_Bindings) on the SDV wiki.

SMAPI 2.x introduced InputEvents, which supports mouse and gamepad events, as well as a wider range of keyboard events.

Thanks!

**Comment by plasticpal** [comment]
Confirmed.

**Comment by rmenessec** [comment]
Has this been fixed? Please reopen if not.

**Comment by pomepome** [comment]
Now, you can use gamepads...
See WhatsNew.md...
